=== Mable-AI/analytics.js/schemas/identify.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "eventType": {
        "type": "string"
      },
      "event": {
        "type": "string"
      },
      "clientId": {
        "type": "string"
      },
      "timestamp": {
        "type": "integer"
      },
      "traits": {
        "type": "object",
        "properties": {
          "sessionId": {
            "type": "string"
          },
          "anonymousId": {
            "type": "string"
          },
          "phoneNumber": {
            "type": ["string", "null"]
          },
          "email": {
            "type": ["string", "null"]
          },
          "shopifyCustomerId": {
            "type": ["string", "null"]
          },
          "fingerprintJsId": {
            "type": ["string", "null"]
          },
          "fbclid": {
            "type": ["string", "null"]
          }
        },
        "required": [
          "sessionId",
          "anonymousId"
        ]
      }
    },
    "required": [
      "eventType",
      "clientId",
      "timestamp",
      "traits"
    ]
  }

=== Mable-AI/analytics.js/examples/identify.event.json
{
    "eventType": "identify",
    "event": "Identify",
    "clientId": "example-shop.myshopify.com",
    "timestamp": 123456789,
    "traits": {
        "sessionId": "c0a8f092-e5e9-48ed-8c6b-423978e7a9a0",
        "anonymousId": "c0a8f092-e5e9-48ed-8c6b-423978e7a9a0",
        "phoneNumber": "555-555-5555",
        "email": "me@example.com",
        "shopifyCustomerId": "123456789",
        "fingerprintJsId": "c0a8f092-e5e9-48ed-8c6b-423978e7a9a0",
        "fbclid": "c0a8f092-e5e9-48ed-8c6b-423978e7a9a0"
    }
}
